//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        public int FORN_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CAFO_CD_ID { get; set; }
        public Nullable<int> TIPE_CD_ID { get; set; }
        public string FORN_NM_NOME { get; set; }
        public string FORN_NM_RAZAO_SOCIAL { get; set; }
        public string FORN_NR_DOCUMENTO { get; set; }
        public string FORM_NM_ENDERECO { get; set; }
        public string FORN_NM_BAIRRO { get; set; }
        public string FORN_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string FORN_NR_CEP { get; set; }
        public string FORN_NR_TELEFONE { get; set; }
        public string FORN_NM_CONTATO { get; set; }
        public string FORN_NM_EMAIL { get; set; }
        public string FORN_DS_DESCRICAO { get; set; }
        public System.DateTime FORN_DT_CADASTRO { get; set; }
        public int FORN_IN_ATIVO { get; set; }
        public string FORN_DS_ESCOPO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CATEGORIA_FORNECEDOR CATEGORIA_FORNECEDOR { get; set; }
        public virtual TIPO_PESSOA TIPO_PESSOA { get; set; }
        public virtual UF UF { get; set; }
    }
}
