//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIDADE()
        {
            this.USUARIO = new HashSet<USUARIO>();
            this.VAGA = new HashSet<VAGA>();
        }
    
        public int UNID_CD_ID { get; set; }
        public int TORR_CD_ID { get; set; }
        public int TIUN_CD_ID { get; set; }
        public string UNID_NR_NUMERO { get; set; }
        public Nullable<int> UNID_IN_ATIVO { get; set; }
        public Nullable<int> UNID_IN_ALUGADA { get; set; }
    
        public virtual TIPO_UNIDADE TIPO_UNIDADE { get; set; }
        public virtual TORRE TORRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAGA> VAGA { get; set; }
    }
}
