//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAGA
    {
        public int VAGA_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public string VAGA_NR_ANDAR { get; set; }
        public string VAGA_NR_NUMERO { get; set; }
        public Nullable<int> VAGA_IN_ATIVO { get; set; }
    
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
